### ISSUE TITLE
Loon with Posit Cloud 

### ISSUE THREAD

**Issue by Missilent** [great-northern-diver/loon.ggplot#68]
Hi Team, 

I am trying to load your package into Posit Cloud ( Rstudio Online ) and it is erroring saying it can not be loaded  with this error
Error: package or namespace load failed for ‘loon’:
 .onLoad failed in loadNamespace() for 'loon', details:
  call: structure(.External(.C_dotTcl, ...), class = "tclObj")
  error: [tcl] couldn't connect to display ":0".

Thanks Fiona

**Comment by rwoldford** [comment]
RStudio online / Posit Cloud is server based and so constrained to using a browser for graphics.
Loon can only be used interactively in a local desktop environment ... on your machine ... not over the internet.
This is because it requires X-Windows for interactive graphics (e.g., Quartz on a Mac).

If you want to use loon, it must be on your desktop.  From there you could use the loon.shiny package to incorporate interactive loon graphics in a browser deployment.

Hope this helps.

**Comment by Missilent** [comment]
Yes, glthanks so much.. I really love Posit..

**Comment by rwoldford** [comment]
You can still use Posit ... just must be the desktop version
